### ISSUE TITLE
Program doesn't run, crash logs in event viewer

### ISSUE THREAD

**Issue by CarlosMerc** [DavidXanatos/priv10#18]
Latest updates on LTSC .net 4.7.2, maybe a kernel/.net issue?

Log Name:      Application
Source:        Application Error
Date:          20/10/2019 11:43:23 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-P3LEOMP
Description:
Faulting application name: PrivateWin10.exe, version: 0.1.8.0, time stamp: 0x5cc99bfe
Faulting module name: KERNELBASE.dll, version: 10.0.17763.831, time stamp: 0xaae01d9e
Exception code: 0xe0434352
Fault offset: 0x0000000000039129
Faulting process id: 0x6a0
Faulting application start time: 0x01d58743f53f50fd
Faulting application path: C:\stuff\PrivateWin10.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: e976fb9c-d2f9-4822-ac90-6bec16fde789
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2019-10-20T12:43:23.709101600Z" />
    <EventRecordID>14544</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-P3LEOMP</Computer>
    <Security />
  </System>
  <EventData>
    <Data>PrivateWin10.exe</Data>
    <Data>0.1.8.0</Data>
    <Data>5cc99bfe</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.17763.831</Data>
    <Data>aae01d9e</Data>
    <Data>e0434352</Data>
    <Data>0000000000039129</Data>
    <Data>6a0</Data>
    <Data>01d58743f53f50fd</Data>
    <Data>C:\stuff\PrivateWin10.exe</Data>
    <Data>C:\Windows\System32\KERNELBASE.dll</Data>
    <Data>e976fb9c-d2f9-4822-ac90-6bec16fde789</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

--------------

Log Name:      Application
Source:        .NET Runtime
Date:          20/10/2019 11:43:23 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-P3LEOMP
Description:
Application: PrivateWin10.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at Windows.Management.Deployment.PackageManager.FindPackages()
   at AppManager.LoadApps()
   at PrivateWin10.Engine.Run()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2019-10-20T12:43:23.676614300Z" />
    <EventRecordID>14543</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-P3LEOMP</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: PrivateWin10.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at Windows.Management.Deployment.PackageManager.FindPackages()
   at AppManager.LoadApps()
   at PrivateWin10.Engine.Run()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

</Data>
  </EventData>
</Event>

**Comment by DavidXanatos** [comment]
This issue will be fixed in the next build which i intent to release in a few weeks.
