### ISSUE TITLE
Crashes at launch [v0.72]

### ISSUE THREAD

**Issue by kekukui** [DavidXanatos/priv10#32]
Faulting application name: PrivateWin10.exe, version: 0.72.0.0, 
Faulting module name: KERNELBASE.dll, version: 10.0.18362.418, 
Exception code: 0xe0434352
Fault offset: 0x000000000003a839

Application: PrivateWin10.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.

Exception Info: **System.NullReferenceException**
   at PrivateWin10.Controls.ProgramListControl.<SortAndFitlerProgList>g__DoSort|15_0(PrivateWin10.ProgramControl, PrivateWin10.ProgramControl)
   at System.Collections.Generic.ArraySortHelper`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].PickPivotAndPartition(System.__Canon[], Int32, Int32, System.Collections.Generic.IComparer`1<System.__Canon>)
   at System.Collections.Generic.ArraySortHelper`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].IntroSort(System.__Canon[], Int32, Int32, Int32, System.Collections.Generic.IComparer`1<System.__Canon>)
   at System.Collections.Generic.ArraySortHelper`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].IntrospectiveSort(System.__Canon[], Int32, Int32, System.Collections.Generic.IComparer`1<System.__Canon>)
   at System.Collections.Generic.ArraySortHelper`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Sort(System.__Canon[], Int32, Int32, System.Collections.Generic.IComparer`1<System.__Canon>)

Exception Info: **System.InvalidOperationException**
   at System.Collections.Generic.ArraySortHelper`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Sort(System.__Canon[], Int32, Int32, System.Collections.Generic.IComparer`1<System.__Canon>)
   at System.Array.Sort[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon[], Int32, Int32, System.Collections.Generic.IComparer`1<System.__Canon>)
   at System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Sort(System.Comparison`1<System.__Canon>)
   at PrivateWin10.Controls.ProgramListControl.SortAndFitlerProgList()
   at PrivateWin10.Controls.ProgramListControl.UpdateProgramList(System.Collections.Generic.List`1<PrivateWin10.ProgramSet>)
   at PrivateWin10.Pages.FirewallPage.SetTreeMode()
   at PrivateWin10.Pages.FirewallPage.SetViewMode(ViewModes)
   at PrivateWin10.Pages.FirewallPage..ctor()
   at PrivateWin10.MainWindow..ctor()
   at PrivateWin10.App.Main(System.String[])

**Comment by DavidXanatos** [comment]
i'll close that as we are at version 0.74 already, pleae report if the isue still hapens with the more recent builds
