### ISSUE TITLE
unable to start service for v0.73+ (and probably lower versions)

### ISSUE THREAD

**Issue by xvids121** [DavidXanatos/priv10#42]
Hi David,

excellent software.  Finally a way to edit firewall rules easily.  Thank you!.

Have the following problems which has effectively preventing it from running.  Wondering if you have any ideas on how to get the service running.   Windows 10 may 1909 - build 18363 (may 1909).   Installed .NET framework 3.5 and worked one time then stopped working.  

- have tried adjusting permissions to full control within program files
- have tried in a C:\temp\PrivateWin10
- tried running from console and administrator in multiple locations with permissions above.

- installed .NET framework 3.5 and it worked fine once.  rebooted and same problem.
- is there some user data file under Appdata or ProgramData which perhaps needs to be removed?

The following is for version 0.73 which is before the improvements for services.

---------
When launched without administrator console but allowing YES to the UAC prompt to grant admin priveleges, the following is output.

C:\Program Files\SECURITY\PrivateWin10>PrivateWin10.exe

C:\Program Files\SECURITY\PrivateWin10>Portable Mode
Config Directory: C:\Program Files\SECURITY\PrivateWin10\Data
Log: PrivateWin10 Process Started, Mode Normal.
Trying to connect to Engine...
Trying to obtain Administrative proivilegs...
Trying to start with 'runas'...

(no more info), executable terminates.
----------

Interestingly the GUI launches and it is run when administrator permissions are DENIED and the log reports the following which I guess would prevent effective application of many features of PrivateWin10.

C:\Program Files\SECURITY\PrivateWin10>Portable Mode
Config Directory: C:\Program Files\SECURITY\PrivateWin10\Data
Log: PrivateWin10 Process Started, Mode Normal.
Trying to connect to Engine...
Trying to obtain Administrative proivilegs...
Trying to start with 'runas'...
Log: TweakManager loaded 183 entries
Your copy of this application is not activated
Log: Exception in RemoteExec: Connection Failed
Log: Exception in RemoteExec: Connection Failed
Log: Exception in TestRegistryTweak: Requested registry access is not allowed.
Log: Tweak Disable AutoLogger-Diagtrack-Listener from Disable Telemetry is not applied!
TestAllTweaks took: 5088ms

(the GUI is then launched, but obviously does not have appropriate permissions).

-----------

Finally, if a console is opened with administrative priveleges and run the following is given.

C:\Program Files\SECURITY\PrivateWin10>Portable Mode
Config Directory: C:\Program Files\SECURITY\PrivateWin10\Data
Log: PrivateWin10 Process Started, Mode Normal.
Trying to connect to Engine...
Log: TweakManager loaded 183 entries
Starting Engine Thread...
Engine Thread Running
Loading program list...
Starting firewall monitor...
Starting firewall guard...
Initializing app manager...
Loading Windows Firewall rules...
Assigning Firewall rules...
Starting Process Monitor...
Log: Failed to initialized ProcessMonitorEtw
Starting Network Monitor...
Log: Failed to initialized NetworkMonitorETW
Setting up IPC host...
Private Win10 Engine started.
... engine started.
Starting engine timer...
Your copy of this application is not activated

Unhandled Exception: System.Runtime.InteropServices.COMException: The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.

The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.

   at NETWORKLIST.NetworkListManagerClass.GetNetworks(NLM_ENUM_NETWORK Flags)
   at PrivateWin10.NetworkMonitor.UpdateNetworks() in F:\Projects\Windows10_Tools\PrivateWin10\PrivateWin10\Core\NetworkMonitor.cs:line 426
   at PrivateWin10.Priv10Engine.OnTimerTick(Object sender, EventArgs e) in F:\Projects\Windows10_Tools\PrivateWin10\PrivateWin10\Core\Priv10Engine.cs:line 258
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at PrivateWin10.Priv10Engine.Run() in F:\Projects\Windows10_Tools\PrivateWin10\PrivateWin10\Core\Priv10Engine.cs:line 224
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Please note that I have also tried installing the setup installation versions as well as uninstalling and installing the services via the -svc_remove and -svc_install switches too with same issue.  As well as attempting to manually start services.

error: 1067 - the service terminated unexpectedly.

Have tried running it under Windows 8 compatability mode too.

**Comment by DavidXanatos** [comment]
Please try the bugfixed release: https://github.com/DavidXanatos/priv10/releases/tag/v0.75b
