### ISSUE TITLE
Crashes at launch [v0.75]

### ISSUE THREAD

**Issue by kekukui** [DavidXanatos/priv10#43]
**Event ID 1026**

Application: PrivateWin10.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.

```
Exception Info: System.Runtime.InteropServices.SEHException
   at <Module>._CxxThrowException(Void*, _s__ThrowInfo*)
   at <Module>.krabs.error_check_common_conditions(UInt32)
   at <Module>.krabs.details.trace_manager<krabs::trace<krabs::details::kt> >.unregister_trace(krabs.details.trace_manager<krabs::trace<krabs::details::kt> >*)
   at <Module>.krabs.details.trace_manager<krabs::trace<krabs::details::kt> >.register_trace(krabs.details.trace_manager<krabs::trace<krabs::details::kt> >*)
   at <Module>.krabs.details.trace_manager<krabs::trace<krabs::details::kt> >.start(krabs.details.trace_manager<krabs::trace<krabs::details::kt> >*)
   at Microsoft.O365.Security.ETW.KernelTrace.Start()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Event ID 1000**

Faulting application name: PrivateWin10.exe, version: 0.75.0.0
Faulting module name: KERNELBASE.dll, version: 6.1.7601.24520
Exception code: `0xe06d7363`
Fault offset: `0x000000000000b87d`

Faulting application path: C:\Program Files\PrivateWin10\PrivateWin10.exe
Faulting module path: `C:\Windows\system32\KERNELBASE.dll`

**Event ID 1**

Exception in IsServiceEnabled: Object reference not set to an instance of an object.

**Event ID 7034**

The Private Win10 service terminated unexpectedly.  It has done this 1 time(s).

**Comment by Mrnofish** [comment]
I've also been getting random crashes since upgrading to 0.75. I doubt Priv10 works for more than an hour after each reboot.

The only way I've found, to avoid crashes, is to keep the window permanently open, but this comes with a cost in terms of resources used.

**Comment by DavidXanatos** [comment]
I found an issue and will release a bugfixed version soon

**Comment by DavidXanatos** [comment]
Please try the bug fixed release:
https://github.com/DavidXanatos/priv10/releases/tag/v0.75b
