### ISSUE TITLE
Priv10 keeps crashing

### ISSUE THREAD

**Issue by Mrnofish** [DavidXanatos/priv10#58]
```
Application: PrivateWin10.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at AppManager.GetAppResourceStr(System.String)
   at System.Windows.Threading.DispatcherOperation`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Windows.Threading.DispatcherOperation.Wait(System.TimeSpan)
   at System.Windows.Threading.Dispatcher.InvokeImpl(System.Windows.Threading.DispatcherOperation, System.Threading.CancellationToken, System.TimeSpan)
   at System.Windows.Threading.Dispatcher.Invoke[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Func`1<System.__Canon>, System.Windows.Threading.DispatcherPriority, System.Threading.CancellationToken, System.TimeSpan)
   at System.Windows.Threading.Dispatcher.Invoke[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Func`1<System.__Canon>)
   at PrivateWin10.Priv10Host.Process(PipeIPC.RemoteCall)
   at PipeIPC.PipeHost+<>c__DisplayClass7_0.<AddListener>b__0(System.Object, Byte[])
   at PipeIPC.IPCStream`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].recvProc()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

===
```
Faulting application name: PrivateWin10.exe, version: 0.75.0.2, time stamp: 0xd7585d48
Faulting module name: KERNELBASE.dll, version: 10.0.19041.388, time stamp: 0x3cc24707
Exception code: 0xe0434352
Fault offset: 0x0000000000023e49
Faulting process id: 0x1be0
Faulting application start time: 0x01d665566b06be3c
Faulting application path: C:\Apps\PrivateWin10\PrivateWin10.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll`
```

**Comment by DavidXanatos** [comment]
please try the new build
