### ISSUE TITLE
Recent inability to run application

### ISSUE THREAD

**Issue by troth13** [DavidXanatos/priv10#64]
After using the application successfully for many months, application does not run after the latest .NET update (though it may be "post hoc propter hoc" on my part). It does run on another PC with the same setup/security/privacy settings. 

Event log:

Application: PrivateWin10.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at PrivateWin10.Priv10Engine.LoadFwRules()
   at PrivateWin10.Priv10Engine.Run()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by DavidXanatos** [comment]
Oh that is not good,
could you try the new 0.8x line of builds?

**Comment by troth13** [comment]
I apologize. While running the .08x build, I discovered the issue: my Wireguard VPN was the offender. .80x build and 75b both run with Wireguard off. Sorry to have taken you away from your tasks for such a stupid oversight on my part. The program is exceptional.
